### ISSUE TITLE
Rendering narrative text

### ISSUE THREAD

**Issue by hickmanw** [danielfrg/jupyter-flex#44] opened 2020-06-17 23:52 UTC
**Does jupyter-flex support rendering of text/narrative in markdown cells, or only through code cells?**

The [layouts documentation page](https://github.com/danielfrg/jupyter-flex/blob/master/docs/layouts.ipynb) says "markdown cells tagged with `text` " can be used to provide narrative text in the dashboard, but the example provided shows a code cell containing a string, tagged with `body`. I suspect the `text` tag reference is a holdover from prior to 0.6.0, but I wonder if the reference to "markdown cell" is also incorrect. 

In 0.6.0, I've found that text in a markdown cell is not rendered (via voila) when tagged with either `text` or `body`, but I am able to render code cells containing strings when they are tagged with `body`.

#### Minimal Working Example Notebook JSON
<summary> The notebook includes both a markdown cell and a code cell tagged with `body`. </summary>
<details>
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Page 1"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Columns 1"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Card 1"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "tags": [
     "body"
    ]
   },
   "source": [
    "A markdown cell tagged with \"body\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "tags": [
     "body"
    ]
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\"A code cell tagged wtih 'body'\""
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\"A code cell tagged with 'body'\""
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
</details>
<img width="139" alt="flex-narrative-mwe" src="https://user-images.githubusercontent.com/39277069/84961599-5c800e80-b0ca-11ea-85ad-1a1b22cba75f.PNG">

P.S. Step 4 on  the [layouts documentation page](https://github.com/danielfrg/jupyter-flex/blob/master/docs/layouts.ipynb) has a typo of "fotter" instead of "footer"

**Comment by danielfrg** [comment] 2020-06-18 17:56
Yes, markdown cells will be rendered in the location that are tagged, `body` being the most common, but you can also have them in the `footer` or the `help` modal.

In the docs they look like code cells because I wanted to show more explicitly that those are cells (markdown will just look like text) but they are meant to be markdown cells.

Look at this example: https://jupyter-flex.extrapolations.dev/examples/card-complete.html and let me know if that helps.

Thanks for pointing out the issues I will fix those now!

**Comment by hickmanw** [comment] 2020-06-18 21:19
Thanks for the reference to that example. It rendered fine on my system via both nbconvert and voila, but helped me discover that markdown cells only render via voila when the `flex_include_source = True` parameter is set. (`flex_include_source` is missing from the [reference page](https://jupyter-flex.extrapolations.dev/reference/).) I think that behavior could be driven by 
https://github.com/danielfrg/jupyter-flex/blob/e596ce18ba17fc237afe41cc4a94e1267ee5c241/python/share/jupyter/voila/templates/flex/nbconvert_templates/flex.j2#L86-L88

Using nbconvert, the markdown cells are always rendered. 

It this is the intended behavior, it would be helpful to mention `flex_include_source` in step 3 of the [layouts page](https://jupyter-flex.extrapolations.dev/layouts/).

**Comment by danielfrg** [comment] 2020-06-18 23:29
Ah I see! that is not the intended behaviour. It was only to hide the source of the code cells by default.

Fixed on: https://github.com/danielfrg/jupyter-flex/pull/45

**Closed** 2020-06-18 23:49 UTC

**Comment by danielfrg** [comment] 2020-06-18 23:59
I made a quick 0.6.1 release with this fix, let me know if you find other issues!

**Comment by hickmanw** [comment] 2020-06-19 01:37
Thanks for the quick fix and release!
