### ISSUE TITLE
widgets not appearing via voila with 0.6.0

### ISSUE THREAD

**Issue by hickmanw** [danielfrg/jupyter-flex#43] opened 2020-06-17 06:54 UTC
ipywidgets are not rendering for me with version 0.6.0, but they do with version 0.5.0. 

#### Minimal working notebook json
<summary> I used a notebook with one section containing one card, with one ToggleButton widget in a code cell tagged with `inputs`. </summary>
<details>
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from ipywidgets import widgets"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Columns 1"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Card 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "tags": [
     "inputs"
    ]
   },
   "outputs": [],
   "source": [
    "widgets.ToggleButton(description=\"one\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
</details>

#### Results
With 0.5.0
<img width="218" alt="flex-mwe_0 5 0" src="https://user-images.githubusercontent.com/39277069/84863233-40cd2780-b03a-11ea-9af0-234867b736a7.PNG">

With 0.6.0
<img width="210" alt="flex-mwe_0 6 0" src="https://user-images.githubusercontent.com/39277069/84863277-53476100-b03a-11ea-8a59-694346240c3e.PNG">

#### Environment
I access voila as an endpoint from a jupyterhub spawned docker image via chrome. I don't see errors in the inspect console with either 0.5.0 or 0.6.0

#### Versions
python : 3.7.6
voila  : 0.1.21
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.14.0
ipykernel        : 5.2.1
jupyter client   : 6.1.3
jupyter lab      : 2.1.1
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.6
traitlets        : 4.3.3

#### Commit hunting
I tried to narrow the range of commits to master at which the change occurs. Widgets appeared for me with 75e444fccac1d74b82c137e0a4a8cd68ef3791cb, but not with 4ece304e364afd8084ee7621f731ae43e75d8147

**Comment by danielfrg** [comment] 2020-06-17 15:25
I think the issue is 0.6.0 removed the `inputs`, `chart` and `text` tags in favor of just `body`.

Could you try changing that and see if that fixes it?

**Comment by hickmanw** [comment] 2020-06-17 21:30
Thank you! That did indeed resolve it. I had seen that `chart` and `text` were replaced, but didn't realize `inputs` was as well.  Step 2 of the [Voila & Widgets example notebook](https://github.com/danielfrg/jupyter-flex/blob/master/docs/voila-ipywidgets.ipynb) still mentions `inputs`.

**Comment by danielfrg** [comment] 2020-06-17 21:40
Thanks for pointing that out! i just fixed it.
Closing but fell free to create other issues if you find any problems :D

**Closed by danielfrg** 2020-06-17 21:40 UTC
